### PR TITLE
Unexpected white area in the verification bottom sheet

### PR DESCRIPTION
**Pull request by ClaireGizard**
#348 

Screenshot_1642168773

Screenshot_1641559738

### CODE REVIEW

**Comment by Florian14** [comment]
IMO the message without the shield image is a bit weird. What is unsecure? I think we should have a complete message to replace the image.
I propose to replace "non sécurisé" by a complete message like "Cette session n'est pas sécurisée." and in the other case "Cette session est sécurisée."
WDYT @giomfo ?

**Comment by giomfo** [comment]
> IMO the message without the shield image is a bit weird. What is unsecure? I think we should have a complete message to replace the image. I propose to replace "non sécurisé" by a complete message like "Cette session n'est pas sécurisée." and in the other case "Cette session est sécurisée." WDYT @giomfo ?

@Florian14 @ClaireGizard I agree to adjust the string.But we will change the string only for the failure case
instead of "non sécurisé", I suggest "La vérification de votre nouvelle session à échouée" or "Votre nouvelle session n'a pas pu être vérifiée"

**Comment by ClaireGizard** [comment]
I prefer the first suggestion. @Florian14  what do you think ?

**Comment by Florian14** [comment]
> I prefer the first suggestion. @Florian14 what do you think ?

Ok for the first one

**Review by Florian14 — APPROVED** [review]
LGTM

**Pull request merged**
