### PR TITLE
[Home screen] Toolbar + Search mode

### PR DESCRIPTION
**Pull request by elghrabi**
#52

### CODE REVIEW

**Review by yostyle — CHANGES_REQUESTED** [review]
After rebase on develop branch the search icon is duplicate on contact screen and the search not working.

**Comment by giomfo** [comment]
TODO:
- remove the legacy search text input
- set up the search in contacts list

**Comment by giomfo** [comment]
I tested the current code, here are 2 comments
- the search is not working on the rooms list
- can we use lowercase for the "Annuler" action?
image

see the design:
image

**Comment by giomfo** [comment]
@Florian14 the search is working correctly on the rooms list now 👍 

I have one more request : the search session is cancelled as soon as a room is selected from the search result. To sum up the search session is cancelled as soon as the user opens another screen (room preview, room, contacts list...)

**Review by yostyle — APPROVED** [review]

**Comment by Florian14** [comment]
> @Florian14 the search is working correctly on the rooms list now 👍
> 
> I have one more request : the search session is cancelled as soon as a room is selected from the search result. To sum up the search session is cancelled as soon as the user opens another screen (room preview, room, contacts list...)

As mentioned together, will be done in dedicated PR.

**Pull request merged**
